services:
  searxng:
    image: docker.io/searxng/searxng:latest
    ports:
      - 4145:8080
    volumes:
      - /home/az/docker/aisearch/searxng:/etc/searxng:rw
    restart: unless-stopped

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - 3001:3001
    environment:
      - SEARXNG_API_URL=http://192.168.1.42:4145
    depends_on:
      - searxng
    volumes:
      - /home/az/docker/aisearch/backend-dbstore:/home/perplexica/data
      - /home/az/docker/aisearch/uploads:/home/perplexica/uploads
      - /home/az/docker/aisearch/config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://backend.aztech.ws/api
        - NEXT_PUBLIC_WS_URL=ws://backend.aztech.ws
    ports:
      - 3000:3000
    depends_on:
      - perplexica-backend
    restart: unless-stopped
